version: '3'
services:
  buildroot:
    build: .
    restart: "no"
    stdin_open: true
    tty: true
    volumes:
      - /root/buildrootsource/output:${HOME}/buildroot/output
      - /root/buildrootsource/dl:${HOME}/buildroot/dl
